### ISSUE TITLE
Numpy version issues while calling NamesMatcher() function

### ISSUE THREAD

**Issue by sak1sham** [athenianco/names-matcher#10]
`File "/usr/local/lib/python3.7/dist-packages/names_matcher/algorithm.py", line 109
    distances = np.ones(((offset := len(parts1)) + len(parts2),) * 2)
                                 ^
SyntaxError: invalid syntax`

While running in colab, I installed the library, and then restarted the runtime environment. But, even after restarting, it gives this error. @athenianco please help.

**Comment by vmarkovtsev** [comment]
I am sorry to say that py 3.7 is not supported.
https://github.com/athenianco/names-matcher/blob/8f177a6a23852bdd1ea01935c3e6f8c131224ab1/setup.py#L39
Unfortunately, we don't plan to support 3.7 because we are using the new syntax everywhere.
